/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.orc;

/**
 * OrcRowSetPredicate could help to skip segments inside Orc file. It uses the value set of required row offsets
 * to match the row offset range of file segment. OrcRowSetPredicate is mostly generated by indices which record
 * the exact row number of indexed value, such as BITMAP Index.
 */
public interface OrcRowSetPredicate
{
    OrcRowSetPredicate TRUE = (start, length) -> true;

    /**
     * Whether the orc segment(Stripe/RowGroup) match predicate, if not, Orc reader can skip this segment.
     *
     * @param start the start row offset of the segment in file.
     * @param length the row number of the segment;
     */
    boolean matches(int start, int length);
}
